container:
  image: node:latest
  cpu: 4

check_task:
  environment:
    CODECOV_NAME: $CIRRUS_TASK_NAME
    CODECOV_TOKEN: ENCRYPTED[65f6fb1a24984a5502638dd2dd4cde45658ac62662fa075a20f30180c19fb5717211e9e7a3d0caa98bdff651dd1c3cef]
    VCS_BRANCH_NAME: $CIRRUS_BRANCH
    VCS_PULL_REQUEST: $CIRRUS_PR
    VCS_TAG: $CIRRUS_TAG
    CI_BUILD_URL: "https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
    CI_BUILD_ID: $CIRRUS_BUILD_ID
    CI_JOB_ID: $CIRRUS_TASK_ID
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  test_script: npm run test
  upload_script: bash <(curl -s https://codecov.io/bash) || echo "Oops! Coverage report upload has failed."

publish_task:
  depends_on:
    - check
  environment:
    NPM_TOKEN: ENCRYPTED[a17b5f2341ac2285c8220b415313aeffac6522f36e9f9092c5d64b9c7403e291be01bd0e5c4432bc3ce948f9f43c12e1]
  only_if: $CIRRUS_USER_COLLABORATOR && $CIRRUS_TAG != ""
  echo_script: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  deploy_script: npm publish
