dist: xenial
language: node_js
node_js:
  - "10"
  - "12"
cache: npm

matrix:
  include:
    - node_js: "10"
      env: COVERAGE=false
    - node_js: "12"
      end: COVERAGE=true

before_install:
  - npm i -g npm

after_success:
  - bash ./coverage.sh

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        on:
          tags: true
