dist: xenial
language: node_js
node_js:
  - "10"
  - "12"
cache: npm

before_install:
  - npm i -g npm

script:
  - npm test
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "12"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        on:
          tags: true
